[package]
name = "firrtl_parser"
version = "0.2.0"
authors = ["tnkmrbg"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest = "2.1.3"
pest_derive = "2.1.0"
thiserror = "1.0"